version: 2.1
orbs:
  newman: postman/newman@0.0.2

jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: yarn
      - newman/newman-run:
          collection: ./src/petstorecollection.json
          # additional-options: -r htmlextra
